# Generated by Django 3.0.5 on 2020-10-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='')),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('thumb', models.ImageField(upload_to='')),
                ('description', models.FileField(null=True, upload_to='')),
                ('summary', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('section_one', models.TextField()),
                ('thumb_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_one_description', models.CharField(blank=True, max_length=50)),
                ('section_two', models.TextField(null=True)),
                ('thumb_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_two_description', models.CharField(blank=True, max_length=50)),
                ('section_three', models.TextField(null=True)),
                ('thumb_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_three_description', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Author')),
                ('category', models.ManyToManyField(blank=True, to='articles.Category')),
            ],
        ),
    ]
