# Generated by Django 3.0.5 on 2020-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
