# Generated by Django 3.0.5 on 2020-12-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201208_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='article',
            name='section_one',
        ),
        migrations.RemoveField(
            model_name='article',
            name='section_three',
        ),
        migrations.RemoveField(
            model_name='article',
            name='section_two',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_one',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_one_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_three',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_three_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_two',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thumb_two_description',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('paragraph', models.TextField(blank=True)),
                ('heading', models.CharField(max_length=50)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
