# Generated by Django 3.0.5 on 2020-12-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201220_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
