# Generated by Django 3.0.5 on 2020-12-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_section_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='thumb',
            new_name='Section_image',
        ),
        migrations.AddField(
            model_name='section',
            name='Section_video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
