# Generated by Django 3.0.5 on 2020-12-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201220_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Section_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Section_video',
            new_name='video',
        ),
    ]
