# Generated by Django 3.0.5 on 2020-12-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201225_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
