# Generated by Django 3.0.5 on 2021-03-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_section_code_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='article',
            new_name='root_article',
        ),
    ]
