# Generated by Django 3.0.5 on 2021-03-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_section_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='image',
            new_name='section_image',
        ),
    ]
