# Generated by Django 3.0.5 on 2020-11-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fav_icon', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('source_link', models.CharField(default='#', max_length=256)),
                ('display_link', models.CharField(default='#', max_length=256)),
                ('buy_link', models.CharField(default='#', max_length=256)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service', models.ManyToManyField(blank=True, to='services.Service')),
            ],
        ),
    ]
