# Generated by Django 3.0.5 on 2020-11-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('htostudios_thumb', models.ImageField(upload_to='')),
                ('htostudios_title', models.CharField(max_length=50)),
                ('htostudios_description', models.TextField()),
                ('harry_thumb', models.ImageField(upload_to='')),
                ('harry_title', models.CharField(max_length=50)),
                ('harry_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_quote_one', models.CharField(max_length=50)),
                ('brand_quote_two', models.CharField(max_length=50)),
            ],
        ),
    ]
