# Generated by Django 3.0.5 on 2020-11-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='harry_intro',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='htostudios_intro',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
